# Generated by Django 4.1 on 2022-08-30 11:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_mailings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailings',
            name='end_date',
            field=models.DateTimeField(verbose_name='End of date to mail'),
        ),
        migrations.AlterField(
            model_name='mailings',
            name='end_time',
            field=models.TimeField(verbose_name='End of time to mail'),
        ),
        migrations.AlterField(
            model_name='mailings',
            name='mailings_id',
            field=models.UUIDField(default=uuid.UUID('ee437714-64d4-4924-9219-ae3e1b92a05e'), verbose_name="Mailing's id"),
        ),
        migrations.AlterField(
            model_name='mailings',
            name='start_date',
            field=models.DateTimeField(verbose_name='Starting date to mail'),
        ),
        migrations.AlterField(
            model_name='mailings',
            name='start_time',
            field=models.TimeField(verbose_name='Starting time to mail'),
        ),
    ]
