# Generated by Django 4.1 on 2022-08-30 11:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_mailings', '0002_alter_mailings_end_date_alter_mailings_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailings',
            name='end_date',
            field=models.DateField(verbose_name='End of date to mail'),
        ),
        migrations.AlterField(
            model_name='mailings',
            name='mailings_id',
            field=models.UUIDField(default=uuid.UUID('dd7a5023-ab78-4094-9712-d93037469de7'), verbose_name="Mailing's id"),
        ),
        migrations.AlterField(
            model_name='mailings',
            name='start_date',
            field=models.DateField(verbose_name='Starting date to mail'),
        ),
    ]
