# Generated by Django 4.1 on 2022-08-30 12:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_mailings', '0004_client_mailings_mobile_operator_code_mailing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.UUIDField(default=uuid.UUID('6b9e5966-8731-41c2-a2a9-4e640d166674'), verbose_name="Client's id"),
        ),
        migrations.AlterField(
            model_name='mailings',
            name='mailings_id',
            field=models.UUIDField(default=uuid.UUID('9964b003-d473-4217-81bf-70d045b091ca'), verbose_name="Mailing's id"),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.UUIDField(default=uuid.UUID('459dcb80-e1b9-44cf-87e6-a4b885347a60'), verbose_name="Message's id"),
        ),
    ]
